# Generated by Django 6.0.4 on 2026-04-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='high_score',
            field=models.IntegerField(default=0),
        ),
    ]
